<?php

namespace App\Filament\Resources\SubjectResource\Pages;

use App\Filament\Resources\SubjectResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateSubject extends CreateRecord
{
    protected static string $resource = SubjectResource::class;
    public function getTitle(): string|Htmlable
    {
        return "Yangi fan qo'shish"; // TODO: Change the autogenerated stub
    }
}
