<?php

namespace App\Filament\Resources\SubjectResource\Pages;

use App\Filament\Resources\SubjectResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Contracts\Support\Htmlable;

class ListSubjects extends ListRecords
{
    protected static string $resource = SubjectResource::class;

    public function getTitle(): string|Htmlable
    {
        return "Fanlar ro'yxati"; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make()->label("Yangi fan yaratish"),
        ];
    }
}
