<?php

namespace App\Filament\Resources\ProblemResource\Pages;

use App\Filament\Resources\ProblemResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateProblem extends CreateRecord
{
    protected static string $resource = ProblemResource::class;
    public function getTitle(): string|Htmlable
    {
        return "Yangi topshiriq qo'shish"; // TODO: Change the autogenerated stub
    }
}
