<?php

namespace App\Filament\Resources\ProblemResource\Pages;

use App\Filament\Resources\ProblemResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Contracts\Support\Htmlable;

class ListProblems extends ListRecords
{
    protected static string $resource = ProblemResource::class;

    public function getTitle(): string|Htmlable
    {
        return "Topshiriqlar ro'yxati"; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make()->label("Yangi topshiriq qo'shish"),
        ];
    }
}
