<?php

namespace App\Filament\Resources\ExamResource\Pages;

use App\Filament\Resources\ExamResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Contracts\Support\Htmlable;

class ListExams extends ListRecords
{
    protected static string $resource = ExamResource::class;

    public function getTitle(): string|Htmlable
    {
        return "Imtihonlar ro'yxati"; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make()->label("Yangi imtihon yaratish"),
        ];
    }
}
