<?php

namespace App\Filament\Resources\StudentResource\Pages;

use App\Filament\Imports\StudentImporter;
use App\Filament\Resources\StudentResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Filament\Tables\Actions\Action;
use Illuminate\Contracts\Support\Htmlable;

class ListStudents extends ListRecords
{
    protected static string $resource = StudentResource::class;

    public function getTitle(): string|Htmlable
    {
        return "O'quvchilar ro'yxati"; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make()
                ->label("Yangi o'quvchi yaratish"),
        ];
    }
}
