<?php

namespace App\Filament\Resources\TeacherResource\Pages;

use App\Filament\Resources\TeacherResource;
use App\Mail\LoginPasswordSend;
use App\Models\Role;
use App\Models\User;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;

class CreateTeacher extends CreateRecord
{
    protected static string $resource = TeacherResource::class;
    public function getTitle(): string|Htmlable
    {
        return "Yangi o'qituvchi qo'shish"; // TODO: Change the autogenerated stub
    }

    public function generateSecurePassword($length = 16):string
    {
        $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_-=+;:,.?';
        $password = '';
        $charLength = strlen($chars) - 1;

        for ($i = 0; $i < $length; $i++) {
            $password .= $chars[random_int(0, $charLength)];
        }

        return $password;
    }

//    public function generateEmail(string $fullName, string $domain = 'gmail.com'): string
//    {
//        // Remove accents and special characters
//        $name = iconv('UTF-8', 'ASCII//TRANSLIT', $fullName);
//
//        // Convert to lowercase and remove non-alphanumeric characters
//        $name = preg_replace('/[^a-z0-9]/', '', strtolower($name));
//
//        return $name . '@' . $domain;
//    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
//        $email = $this->generateEmail($data['full_name']);
        $password = $this->generateSecurePassword(12);

        $user = User::create([
            'name' => $data['full_name'],
            'maktab_id' => $data['maktab_id'],
            'email' => $data['email'],
            'password' => Hash::make($password),
            'role_id' => Role::where('name', 'teacher')->value('id'),
        ]);

        // Set this user's ID in the teacher
        $data['user_id'] = $user->id;

        // Optionally: store plain password to show after creation
        $recipient = auth()->user();

        // Sending creadentials via email
        Mail::to($data['email'])->queue(new LoginPasswordSend($data['email'], $password));


        // Notify the the admin also
        Notification::make()
            ->title('Your credentials are ready!')
            ->color('green')
            ->body("Email: {$data['email']} \n Password: {$password}")
            ->sendToDatabase($recipient);
        session()->flash('generated_password', $password);

        unset($data['email']);
        return $data;
    }

    protected function getRedirectUrl(): string
    {
        return '/teachers';
    }
}
