<?php

namespace App\Filament\Resources\TeacherResource\Pages;

use App\Filament\Resources\TeacherResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateTeacher extends CreateRecord
{
    protected static string $resource = TeacherResource::class;
    public function getTitle(): string|Htmlable
    {
        return "Yangi o'qituvchi qo'shish"; // TODO: Change the autogenerated stub
    }
}
