<?php

namespace App\Filament\Resources\TeacherResource\Pages;

use App\Filament\Resources\TeacherResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Contracts\Support\Htmlable;

class ListTeachers extends ListRecords
{
    protected static string $resource = TeacherResource::class;

    public function getTitle(): string|Htmlable
    {
        return "O'qituvchilar ro'yxati"; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make()->label("Yangi o'qituvchi yaratish"),
        ];
    }
}
