<?php

namespace App\Filament\Resources\MarkResource\Pages;

use App\Filament\Resources\MarkResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Contracts\Support\Htmlable;

class ListMarks extends ListRecords
{
    protected static string $resource = MarkResource::class;

    public function getTitle(): string|Htmlable
    {
        return "Baholar ro'yxati"; // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make()->label("Yangi baho qo'shish"),
        ];
    }
}
