<?php

namespace App\Filament\Resources\MaktabResource\Pages;

use App\Filament\Resources\MaktabResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Database\Eloquent\Model;

class CreateMaktab extends CreateRecord
{
    protected static string $resource = MaktabResource::class;
    protected function getRedirectUrl(): string
    {
        return "/maktabs/";
    }

    public function getTitle(): string|Htmlable
    {
        return "Yangi maktab yaratish"; // TODO: Change the autogenerated stub
    }


}
