<?php

namespace App\Filament\Resources\SinfResource\Pages;

use App\Filament\Resources\SinfResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateSinf extends CreateRecord
{
    protected static string $resource = SinfResource::class;

    public function getTitle(): string|Htmlable
    {
        return "Yangi sinf yaratish"; // TODO: Change the autogenerated stub
    }
}
