<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateUser extends CreateRecord
{
    protected static string $resource = UserResource::class;
    public function getTitle(): string|Htmlable
    {
        return "Yangi foydalanuvchi qo'shish"; // TODO: Change the autogenerated stub
    }
}
